name: lambda-api

on:
  pull_request:
    paths:
      - 'api/**'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      node_version: 14.x
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${node_version}
        uses: actions/setup-node@v3
        with:
          node-version: ${node_version}
      - run: cd api && yarn
